Repository oslokommune/okctl, pull requests merged in 2021-02, with the labels that each got.

#267 feat(kaex): Add tests
  cmd/okctl/scaffoldapplication.go
  go.mod
  go.sum
  pkg/client/core/service_application_client_test.go
  pkg/client/core/testdata/my-app-application.yaml.golden
  pkg/client/core/testdata/my-app.yaml.golden
  pkg/scaffold/ingress_test.go
  pkg/scaffold/template.go
  pkg/scaffold/template_test.go
Labels: enhancement

#271 feat(declarativecluster): Add userdocs for declarative cluster
  userdocs/mkdocs.yml
  userdocs/src/beta/declarativecluster.md
Labels: documentation

#280 [KM142] Cloud formation stack outputs should also be exported, add DBSubnetGroupName output
  docs/release_notes/0.0.39.md
  pkg/cfn/components/certificate/testdata/certificate.golden
  pkg/cfn/components/composer.go
  pkg/cfn/components/dbsubnetgroup/dbsubnetgroup.go
  pkg/cfn/components/dbsubnetgroup/dbsubnetgroup_test.go
  pkg/cfn/components/dbsubnetgroup/testdata/dbsubnetgroup.json.golden
  pkg/cfn/output.go
  pkg/cfn/output_test.go
  pkg/cfn/testdata/alb-ingress-cloudformation.yaml.golden
  pkg/cfn/testdata/esp-cloudformation.yaml.golden
  pkg/cfn/testdata/external-dns-cloudformation.yaml.golden
  pkg/cfn/testdata/public-certificate-cf.yaml.golden
  pkg/cfn/testdata/userpool-client.yaml.golden
  pkg/cfn/testdata/vpc-cloudformation.yaml.golden
  pkg/cfn/testdata/vpc-minimal-cf.yaml.golden
Labels: enhancement

#273 ✅ Add service user auth
  cmd/okctl/applycluster.go
  docs/release_notes/0.0.39.md
  pkg/context/context.go
  pkg/credentials/aws/aws.go
  pkg/credentials/aws/aws_test.go
  pkg/okctl/okctl.go
Labels: enhancement

#298 ✅ Add RFC for RFC framework
  docs/rfc/0000-rfc-template.md
  docs/rfc/0001-select-rfc-framework.md
Labels: documentation

#299 [KM34] Tag all cloud formation resources created by okctl
  .goreleaser-local.yml
  .goreleaser.yml
  cmd/okctl/create.go
  cmd/okctl/version.go
  pkg/apis/eksctl.io/v1alpha5/clusterconfig_v1alpha5.go
  pkg/apis/okctl.io/v1alpha1/types.go
  pkg/cfn/runner.go
  pkg/clusterconfig/clusterconfig.go
  pkg/clusterconfig/testdata/aws-alb-ingres-controller.golden
  pkg/clusterconfig/testdata/clusterConfig.golden
  pkg/clusterconfig/testdata/external-dns.golden
  pkg/clusterconfig/testdata/externalSecretsServiceAccount.golden
  pkg/clusterconfig/testdata/minimal-cluster-config.golden
  pkg/clusterconfig/testdata/serviceAccount.golden
  pkg/config/config.go
  pkg/version/doc.go
  pkg/version/release.go
  pkg/version/version.go
Labels: enhancement

#315 Add resource overview
  userdocs/mkdocs.yml
  userdocs/src/about/resources.md
  userdocs/src/img/okctl-resource-overview.png
  userdocs/src/img/resource_dependencies.png
Labels: documentation

#321 🐛 Fix declarative missing argocd and cognito
  cmd/okctl/applycluster.go
  docs/release_notes/0.0.41.md
  pkg/controller/convert.go
  pkg/controller/convert_test.go
  pkg/controller/reconciler/argocd_reconciler.go
  pkg/controller/reconciler/github_reconciler.go
  pkg/controller/reconciler/identitymanager_reconciler.go
  pkg/controller/reconciler/zone_reconciler.go
  pkg/controller/refreshers.go
  pkg/controller/synchronize.go
Labels: enhancement

#324 [KM121] Add names to the VPC and subnets so that they are easier to distinguish
  pkg/cfn/components/subnet/subnet.go
  pkg/cfn/components/vpc/vpc.go
  pkg/cfn/testdata/vpc-cloudformation.yaml.golden
  pkg/cfn/testdata/vpc-minimal-cf.yaml.golden
Labels: verified

#343 👌 Remove reconciliation manager
  cmd/okctl/applycluster.go
  pkg/controller/reconciler/albingresscontroller_reconciler.go
  pkg/controller/reconciler/argocd_reconciler.go
  pkg/controller/reconciler/autoscaler_reconciler.go
  pkg/controller/reconciler/awsloadbalancercontroller_reconciler.go
  pkg/controller/reconciler/blockstorage_reconciler.go
  pkg/controller/reconciler/cluster_reconciler.go
  pkg/controller/reconciler/composite_reconciler.go
  pkg/controller/reconciler/externaldns_reconciler.go
  pkg/controller/reconciler/externalsecrets.go
  pkg/controller/reconciler/github_reconciler.go
  pkg/controller/reconciler/identitymanager_reconciler.go
  pkg/controller/reconciler/nameserverdelegator_reconciler.go
  pkg/controller/reconciler/noop.go
  pkg/controller/reconciler/primary_hostedzone_reconciler.go
  pkg/controller/reconciler/reconciler.go
  pkg/controller/reconciler/vpc_reconciler.go
  pkg/controller/resourcetree/tree.go
  pkg/controller/synchronize.go
Labels: enhancement, go

#342 ✅ Add nightly test
  .github/workflows/nightly.yaml
  cmd/okctl/applycluster.go
  cmd/okctl/delete.go
  pkg/client/core/api/rest/github.go
  pkg/client/core/service_github.go
  pkg/controller/reconciler/albingresscontroller_reconciler.go
  pkg/controller/reconciler/argocd_reconciler.go
  pkg/controller/reconciler/autoscaler_reconciler.go
  pkg/controller/reconciler/awsloadbalancercontroller_reconciler.go
  pkg/controller/reconciler/blockstorage_reconciler.go
  pkg/controller/reconciler/cluster_reconciler.go
  pkg/controller/reconciler/composite_reconciler.go
  pkg/controller/reconciler/externaldns_reconciler.go
  pkg/controller/reconciler/externalsecrets.go
  pkg/controller/reconciler/github_reconciler.go
  pkg/controller/reconciler/identitymanager_reconciler.go
  pkg/controller/reconciler/nameserverdelegator_reconciler.go
  pkg/controller/reconciler/noop.go
  pkg/controller/reconciler/primary_hostedzone_reconciler.go
  pkg/controller/reconciler/reconciler.go
  pkg/controller/reconciler/vpc_reconciler.go
  pkg/controller/resourcetree/tree.go
  pkg/controller/synchronize.go
  pkg/helm/charts/awslbc/awslbc.go
  pkg/kube/manifests/echoserver/echoserver.go
  pkg/spinner/spinner.go
  pkg/virtualenv/testhelper_test.go
Labels: enhancement, go

#349 🐛 Fix kubepromstack dependency
  docs/release_notes/0.0.42.md
  pkg/controller/convert.go
  pkg/controller/convert_test.go
Labels: bug

#357 KM178 🐛 Fix diff tree shallow copy
  docs/release_notes/0.0.43.md
  pkg/controller/synchronize.go
Labels: bug

#356 👌 Move NS record delegation test to after cluster
  cmd/okctl/applycluster.go
  docs/release_notes/0.0.43.md
  pkg/controller/convert.go
  pkg/controller/reconciler/nameserverdelegator_reconciler.go
  pkg/controller/reconciler/nameserversdelegatedtest_reconciler.go
  pkg/controller/resourcetree/tree.go
  pkg/domain/domain.go
Labels: enhancement

#361 KM156 👌 Update documentation WIP
  userdocs/.gitignore
  userdocs/mkdocs.yml
  userdocs/src/buildingblocks/argocd.md
  userdocs/src/buildingblocks/cloud.md
  userdocs/src/buildingblocks/github.md
  userdocs/src/buildingblocks/kubernetes.md
  userdocs/src/deployment/argocd.md
  userdocs/src/getting-started/clean-up.md
  userdocs/src/getting-started/create-application.md
  userdocs/src/getting-started/create-cluster.md
  userdocs/src/getting-started/install.md
  userdocs/src/getting-started/prerequisites.md
  userdocs/src/getting-started/run-virtual-environment.md
  userdocs/src/getting-started/view-bundled-applications.md
  userdocs/src/help/common-issues.md
  userdocs/src/help/docker-registry.md
  userdocs/src/help/faq.md
  userdocs/src/help/outdated-common-issues.md
  userdocs/src/img/authorize.png
  userdocs/src/img/device-auth.png
  userdocs/src/img/enter-code.png
  userdocs/src/img/repository-name.png
  userdocs/src/img/team.png
  userdocs/src/index.md
  userdocs/src/usage/adduser.md
  userdocs/src/usage/applicationyaml.md
  userdocs/src/usage/testcluster.md
  userdocs/theme/assets/stylesheets/button.css
  userdocs/theme/assets/stylesheets/center-container.css
  userdocs/theme/assets/stylesheets/theme.css
  userdocs/theme/partials/header.html
Labels: documentation, in progress
