Repository oslokommune/okctl, pull requests merged in 2021-04, with the labels that each got.

#456 KM230 👌 Convert apply application to reconciliation pattern
  cmd/okctl/apply_application.go
  docs/release_notes/0.0.54.md
  pkg/client/application_client.go
  pkg/client/application_client_test.go
  pkg/client/core/service_application_client.go
  pkg/client/core/service_application_client_test.go
  pkg/client/core/testdata/argocd-application.yaml.golden
  pkg/commands/apply_application.go
  pkg/controller/convert.go
  pkg/controller/reconciler/application_reconciler.go
  pkg/controller/resourcetree/tree.go
  pkg/controller/synchronize.go
  pkg/controller/synchronize_test.go
  pkg/okctl/okctl.go
Labels: enhancement

#461 ✅ Add database configuration to scaffold cluster
  docs/release_notes/0.0.55.md
  pkg/commands/scaffoldcluster.go
  pkg/commands/scaffoldcluster_test.go
  pkg/commands/testdata/Should scaffold cluster declaration based on opts.golden
  userdocs/src/getting-started/create-cluster.md
Labels: documentation

#459 ✅ Add users setting to scaffold cluster
  docs/release_notes/0.0.55.md
  pkg/commands/scaffoldcluster.go
  pkg/commands/testdata/Should scaffold cluster declaration based on opts.golden
  userdocs/src/getting-started/create-cluster.md
Labels: documentation

#448 KM182 ✅ Add ECR provisioning
  cmd/okctl/apply_application.go
  pkg/api/container_repository_api.go
  pkg/api/core/cloudprovider/aws/container_repository_aws.go
  pkg/api/core/endpoint_container_repository.go
  pkg/api/core/handler_api.go
  pkg/api/core/service_container_repository_api.go
  pkg/cfn/components/composer.go
  pkg/cfn/components/containerrepository/containerrepository.go
  pkg/cfn/namer.go
  pkg/client/application_client.go
  pkg/client/container_repository_client.go
  pkg/client/core/api/rest/container_repository_rest.go
  pkg/client/core/handler_client.go
  pkg/client/core/service_application_client.go
  pkg/client/core/service_container_repository_client.go
  pkg/client/core/state/storm/container_repository_state.go
  pkg/client/core/state/storm/container_repository_state_test.go
  pkg/client/mock/mock.go
  pkg/config/constant/api.go
  pkg/okctl/okctl.go
Labels: enhancement

#466 👌 Increase debug output for argocd.Create service call
  pkg/client/core/service_argocd_client.go
Labels: enhancement

#464 [NOTASK] Establish a janitor that helps us keep things under control
  .github/actions/janitor/action.yml
  .github/actions/janitor/entrypoint.sh
  .github/workflows/janitor.yaml
  .gitignore
  Dockerfile
  cmd/janitor/hostedzone.go
  cmd/janitor/main.go
  pkg/cloud/provider.go
  pkg/domain/domain.go
  pkg/janitor/hostedzone/hostedzone.go
  pkg/janitor/hostedzone/hostedzone_test.go
  pkg/mock/aws.go
Labels: enhancement, verified

#473 👌 KM239 Rewrite application to fit into okctl.io/v1alpha1 namespace
  cmd/okctl/apply_application.go
  cmd/okctl/scaffold_application.go
  docs/release_notes/0.0.55.md
  pkg/apis/okctl.io/v1alpha1/application_v1alpha1.go
  pkg/apis/okctl.io/v1alpha1/application_v1alpha1_test.go
  pkg/client/application_client.go
  pkg/client/core/service_application_client.go
  pkg/client/core/service_application_client_test.go
  pkg/commands/apply_application.go
  pkg/commands/scaffoldapplication.go
  pkg/commands/scaffoldapplication_test.go
  pkg/commands/testdata/Should scaffold application declaration based on opts.golden
  pkg/controller/reconciler/application_reconciler.go
  pkg/controller/resourcetree/tree.go
  pkg/scaffold/api.go
  pkg/scaffold/template.go
  pkg/scaffold/template_test.go
  pkg/scaffold/testdata/scaffoldWithOpts.golden
Labels: enhancement

#475 ✅ Add fetch declaration path from env var
  cmd/okctl/main.go
  docs/release_notes/0.0.55.md
  pkg/config/constant/api.go
  pkg/config/load/repository.go
Labels: bug

#488 KM182 ✅ Add ECR reconciler
  cmd/okctl/apply_application.go
  cmd/okctl/version.go
  docs/release_notes/0.0.55.md
  go.mod
  go.sum
  pkg/apis/okctl.io/v1alpha1/application_v1alpha1.go
  pkg/apis/okctl.io/v1alpha1/application_v1alpha1_test.go
  pkg/cfn/components/containerrepository/containerrepository.go
  pkg/client/container_repository_client.go
  pkg/client/core/service_application_client.go
  pkg/client/core/service_application_client_test.go
  pkg/client/core/state/storm/container_repository_state.go
  pkg/client/core/state/storm/container_repository_state_test.go
  pkg/client/core/testdata/ingress.yaml.golden
  pkg/client/mock/mock.go
  pkg/commands/apply_application.go
  pkg/commands/apply_application_test.go
  pkg/commands/scaffoldapplication.go
  pkg/commands/scaffoldapplication_test.go
  pkg/commands/testdata/Should scaffold application declaration based on opts.golden
  pkg/commands/testdata/TestApplyApplicationSuccessMessage/Should_get_expected_success_message_when_using_image_URI.golden
  pkg/commands/testdata/TestApplyApplicationSuccessMessage/Should_get_expected_success_message_when_using_image_name.golden
  pkg/controller/convert.go
  pkg/controller/reconciler/application_reconciler.go
  pkg/controller/reconciler/container_repository_reconciler.go
  pkg/controller/resourcetree/tree.go
  pkg/controller/synchronize.go
  pkg/scaffold/api.go
  pkg/scaffold/convert.go
  pkg/scaffold/resources/argo.go
  pkg/scaffold/resources/convert.go
  pkg/scaffold/resources/defaults.go
  pkg/scaffold/resources/deployment.go
  pkg/scaffold/resources/doc.go
  pkg/scaffold/resources/ingress.go
  pkg/scaffold/resources/persistentvolumeclaim.go
  pkg/scaffold/resources/service.go
  userdocs/src/getting-started/create-application.md
Labels: enhancement

#492 ✅ Add default dnsPolicy to apply application podspec
  docs/release_notes/0.0.56.md
  pkg/client/core/testdata/deployment.yaml.golden
  pkg/scaffold/resources/deployment.go
Labels: enhancement

#498 [KM210] Don't use physical names for logical IDs
  pkg/api/core/cloudprovider/aws/component_aws.go
  pkg/cfn/builder_test.go
  pkg/cfn/components/composer.go
  pkg/cfn/components/lambdafunction/lambdafunction.go
  pkg/cfn/components/lambdafunction/testdata/rotate-lambda-patched.yaml.golden
  pkg/cfn/components/lambdafunction/testdata/rotate-lambda.yaml.golden
  pkg/cfn/components/role/role.go
  pkg/cfn/components/role/role_test.go
  pkg/cfn/components/s3bucket/s3bucket_test.go
  pkg/cfn/components/s3bucket/testdata/s3bucket.yaml.golden
  pkg/cfn/components/securitygroup/securitygroup.go
  pkg/cfn/components/securitygroup/securitygroup_test.go
  pkg/cfn/testdata/rds-postgres.yaml.golden
  pkg/cfn/testdata/s3-bucket.yaml.golden
Labels: verified

#500 [NOTASK] Cleaner should use domain to find certificate arn
  pkg/acmapi/acmapi.go
  pkg/acmapi/acmapi_test.go
  pkg/api/certificate_api.go
  pkg/api/core/cloudprovider/aws/certificate_aws.go
  pkg/api/core/service_identitymanager_api.go
  pkg/api/identitymanager_api.go
  pkg/cleaner/cleaner.go
  pkg/cleaner/cleaner_test.go
  pkg/client/certificate_client.go
  pkg/client/core/service_argocd_client.go
  pkg/client/core/service_certificate_client.go
  pkg/client/core/service_identitymanager_client.go
  pkg/client/core/service_monitoring_client.go
  pkg/mock/aws.go
Labels: verified

#499 [KM247] Fix the cleanup reconcilers
  cmd/okctl/delete.go
  go.mod
  go.sum
  pkg/controller/convert.go
  pkg/controller/convert_test.go
  pkg/controller/resourcetree/tree.go
  pkg/controller/synchronize.go
Labels: verified
