Repository oslokommune/okctl, pull requests merged in 2021-03, with the labels that each got.

#365 👌 Improve buttons and gopher in okctl.io
  userdocs/theme/assets/stylesheets/button.css
  userdocs/theme/assets/stylesheets/center-container.css
Labels: enhancement

#379 KM189 👌 Increase debug information to better localize bug
  pkg/helm/helm.go
Labels: enhancement

#377 KM162 👌 Implement application support for multiple environments
  cmd/okctl/applyapplication.go
  cmd/okctl/scaffoldapplication.go
  docs/release_notes/0.0.44.md
  go.mod
  pkg/client/application_client.go
  pkg/client/core/service_application_client.go
  pkg/client/core/service_application_client_test.go
  pkg/client/core/store/filesystem/application_filesystem.go
  pkg/client/core/testdata/argocd-application.yaml.golden
  pkg/client/core/testdata/deployment.yaml.golden
  pkg/client/core/testdata/ingress-patch.yaml.golden
  pkg/client/core/testdata/ingress.yaml.golden
  pkg/client/core/testdata/kustomization-base.yaml.golden
  pkg/client/core/testdata/kustomization-overlay.yaml.golden
  pkg/client/core/testdata/service.yaml.golden
  pkg/client/core/testdata/volumes.yaml.golden
  pkg/config/config.go
  pkg/okctl/okctl.go
  pkg/scaffold/api.go
  pkg/scaffold/deployment.go
  pkg/scaffold/ingress.go
  pkg/scaffold/ingress_test.go
  pkg/scaffold/overlay.go
  pkg/scaffold/resources/argo.go
  pkg/scaffold/resources/convert.go
  pkg/scaffold/resources/defaults.go
  pkg/scaffold/resources/ingress.go
  pkg/scaffold/resources/kustomization.go
  pkg/scaffold/resources/patch.go
  pkg/scaffold/resources/patch_test.go
  pkg/scaffold/template.go
  pkg/scaffold/template_test.go
  pkg/scaffold/testdata/scaffoldOkctlApplication.golden
  pkg/scaffold/testdata/scaffoldWithOpts.golden
  userdocs/src/getting-started/create-application.md
Labels: enhancement

#381 [KM190] Enable logging of Fargate containers to cloud watch
  docs/release_notes/0.0.45.md
  docs/release_notes/0.0.46.md
  pkg/apis/okctl.io/v1alpha1/provider_v1alpha1.go
  pkg/cfn/builder_test.go
  pkg/cfn/components/composer.go
  pkg/cfn/namer.go
  pkg/cfn/testdata/fargate-cloudwatch.yaml.golden
  pkg/client/core/service_monitoring_client.go
  pkg/cloud/provider.go
  pkg/eksapi/eksapi.go
  pkg/eksapi/eksapi_test.go
  pkg/iamapi/iamapi.go
  pkg/iamapi/iamapi_test.go
  pkg/mock/aws.go
  pkg/okctl/okctl.go
Labels: enhancement, verified

#393 KM184 👌 Clean up cluster declaration
  .github/workflows/nightly.yaml
  cmd/okctl/applycluster.go
  cmd/okctl/create.go
  cmd/okctl/createtestcluster.go
  cmd/okctl/scaffoldcluster.go
  cmd/okctl/show.go
  docs/release_notes/0.0.47.md
  pkg/api/core/run/helm_run.go
  pkg/apis/okctl.io/v1alpha1/cluster_v1alpha1.go
  pkg/apis/okctl.io/v1alpha1/cluster_v1alpha1_test.go
  pkg/apis/okctl.io/v1alpha1/testdata/default-cluster.yml.golden
  pkg/apis/okctl.io/v1alpha1/testdata/empty-cluster.yml.golden
  pkg/ask/ask.go
  pkg/client/core/api/git/nameserverdelegator_api.go
  pkg/client/core/service_application_client.go
  pkg/client/core/service_application_client_test.go
  pkg/client/core/service_argocd_client.go
  pkg/client/core/service_monitoring_client.go
  pkg/client/core/store/filesystem/application_filesystem.go
  pkg/clusterconfig/clusterconfig_test.go
  pkg/commands/applycluster.go
  pkg/commands/scaffoldcluster.go
  pkg/commands/scaffoldcluster_test.go
  pkg/commands/testdata/Should scaffold cluster declaration based on opts.golden
  pkg/commands/venv.go
  pkg/config/config.go
  pkg/config/constant/api.go
  pkg/config/load/repository.go
  pkg/config/load/user.go
  pkg/config/state/repository.go
  pkg/controller/convert.go
  pkg/controller/convert_test.go
  pkg/controller/reconciler/argocd_reconciler.go
  pkg/controller/reconciler/cluster_reconciler.go
  pkg/controller/reconciler/externaldns_reconciler.go
  pkg/controller/reconciler/identitymanager_reconciler.go
  pkg/controller/reconciler/kubeprometheusstack_reconciler.go
  pkg/controller/reconciler/nameserverdelegator_reconciler.go
  pkg/controller/reconciler/nameserversdelegatedtest_reconciler.go
  pkg/controller/reconciler/primary_hostedzone_reconciler.go
  pkg/controller/refreshers.go
  pkg/controller/synchronize.go
  pkg/controller/synchronize_test.go
  pkg/helm/charts/loki/loki.go
  pkg/helm/charts/promtail/promtail.go
  pkg/helm/charts/tempo/tempo.go
  pkg/helm/helm_test.go
  pkg/keyring/keyring.go
  pkg/okctl/okctl.go
  pkg/scaffold/api.go
  userdocs/src/getting-started/create-cluster.md
Labels: documentation, enhancement

#414 🐛 Fix externaldns type override
  pkg/api/core/run/kube_run.go
  pkg/api/core/service_kube.go
  pkg/api/core/service_kube_test.go
Labels: bug

#410 ✅ Add requeue to identitymanager upon timeout
  docs/release_notes/0.0.49.md
  pkg/api/core/service_identitymanager_api.go
  pkg/api/core/service_identitymanager_api_test.go
  pkg/controller/reconciler/identitymanager_reconciler.go
Labels: bug

#417 🐛 Fix server side errors getting muted
  docs/release_notes/0.0.50.md
  pkg/client/core/api/rest/client.go
Labels: bug

#421 ✅ Add dynamic port for server side
  docs/release_notes/0.0.52.md
  pkg/config/config.go
Labels: enhancement

#418 [KM198] Create a Postgres port forwarder
  cmd/okctl/applycluster.go
  cmd/okctl/forward.go
  cmd/okctl/forward_postgres.go
  cmd/okctl/main.go
  docs/release_notes/0.0.53.md
  docs/release_notes/0.0.54.md
  go.mod
  go.sum
  pkg/context/context.go
  pkg/kube/forward/forward.go
  pkg/kube/manifests/pgbouncer/pgbouncer.go
  pkg/kube/manifests/pgbouncer/pgbouncer_test.go
  pkg/kube/manifests/pgbouncer/testdata/pod.golden
  pkg/kube/manifests/pgbouncer/testdata/secret.golden
  pkg/kube/manifests/psqlclient/psql.go
  pkg/kube/pod/pod.go
  pkg/middleware/logger/logger.go
  pkg/middleware/logger/logger_test.go
  userdocs/src/getting-started/application-addons.md
Labels: enhancement, verified
