Repository oslokommune/okctl, pull requests merged in 2021-05, with the labels that each got.

#510 👌 Use custom hello world image for scaffold application
  docs/release_notes/0.0.57.md
  pkg/commands/scaffoldapplication.go
  pkg/commands/testdata/Should scaffold application declaration based on opts.golden
Labels: enhancement

#513 👌 Improve scaffolded service for prometheus integration
  docs/release_notes/0.0.59.md
  pkg/client/core/testdata/service.yaml.golden
  pkg/scaffold/resources/service.go
Labels: enhancement

#516 👌 Bump hello-okctl scaffold application image
  pkg/commands/scaffoldapplication.go
  pkg/commands/testdata/Should scaffold application declaration based on opts.golden
Labels: enhancement

#537 KM270 🐛 Fix linter issue in CI by bumping it
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  cmd/okctl/main.go
  cmd/okctl/show.go
  pkg/acmapi/acmapi.go
  pkg/api/core/transport_helm.go
  pkg/api/core/transport_kube.go
  pkg/cleaner/cleaner.go
  pkg/client/core/service_awsloadbalancercontroller_client.go
  pkg/client/core/service_component.go
  pkg/client/core/service_monitoring_client.go
  pkg/client/mock/mock.go
  pkg/controller/synchronize.go
  pkg/elbv2api/elbv2api.go
  pkg/git/git.go
  pkg/helm/charts/argocd/argocd.go
  pkg/helm/helm.go
  pkg/kube/pod/pod.go
  pkg/scaffold/api.go
Labels: bug

#525 [NOTASK] Make helm timeouts easier to configure
  pkg/client/core/service_argocd_client.go
  pkg/client/core/service_autoscaler.go
  pkg/client/core/service_awsloadbalancercontroller_client.go
  pkg/client/core/service_blockstorage.go
  pkg/client/core/service_externalsecrets.go
  pkg/client/core/service_monitoring_client.go
  pkg/controller/convert.go
  pkg/helm/charts/argocd/argocd.go
  pkg/helm/charts/autoscaler/autoscaler.go
  pkg/helm/charts/awslbc/awslbc.go
  pkg/helm/charts/blockstorage/blockstorage.go
  pkg/helm/charts/externalsecrets/externalsecrets.go
  pkg/helm/charts/kubepromstack/kubepromstack.go
  pkg/helm/charts/loki/loki.go
  pkg/helm/charts/promtail/promtail.go
  pkg/helm/charts/tempo/tempo.go
  pkg/helm/helm_test.go
Labels: preview

#523 [NOTASK] Make it possible to choose database
  cmd/okctl/forward_postgres.go
  pkg/kube/manifests/pgbouncer/pgbouncer.go
  pkg/kube/manifests/pgbouncer/pgbouncer_test.go
  pkg/kube/manifests/pgbouncer/testdata/default-pod.golden
  pkg/kube/manifests/pgbouncer/testdata/pod-with-database.golden
Labels: preview

#531 KM191 ✅ Add Prometheus integration to application.yaml
  docs/release_notes/0.0.60.md
  go.mod
  go.sum
  pkg/apis/okctl.io/v1alpha1/application_v1alpha1.go
  pkg/apis/okctl.io/v1alpha1/application_v1alpha1_test.go
  pkg/client/application_client.go
  pkg/client/core/service_application_client.go
  pkg/client/core/service_application_client_test.go
  pkg/client/core/store/filesystem/application_filesystem.go
  pkg/client/core/testdata/kustomization-base.yaml.golden
  pkg/client/core/testdata/service-monitor.yaml.golden
  pkg/commands/scaffoldapplication.go
  pkg/commands/testdata/Should scaffold application declaration based on opts.golden
  pkg/scaffold/api.go
  pkg/scaffold/resources/service.go
  pkg/scaffold/resources/servicemonitor.go
  userdocs/src/getting-started/monitoring.md
Labels: enhancement

#559 KM281 🐛 Move ArgoCD CRD to env specific folder
  cmd/okctl/apply_application.go
  docs/release_notes/0.0.62.md
  pkg/client/core/service_application_client_test.go
  pkg/client/core/store/filesystem/application_filesystem.go
  pkg/commands/apply_application.go
  pkg/commands/apply_application_test.go
  pkg/commands/testdata/TestApplyApplicationSuccessMessage/Should_get_expected_success_message_when_using_image_URI.golden
  pkg/commands/testdata/TestApplyApplicationSuccessMessage/Should_get_expected_success_message_when_using_image_name.golden
  userdocs/src/getting-started/create-application.md
Labels: bug

#560 KM284 🐛 Fix base/deployment.yaml containing env specific attribute image:
  docs/release_notes/0.0.62.md
  pkg/client/core/service_application_client_test.go
  pkg/client/core/store/filesystem/application_filesystem.go
  pkg/client/core/testdata/deployment-patch.yaml.golden
  pkg/client/core/testdata/deployment.yaml.golden
  pkg/client/core/testdata/kustomization-overlay.yaml.golden
  pkg/config/constant/api.go
  pkg/scaffold/api.go
  pkg/scaffold/resources/deployment.go
Labels: bug

#553 KM279 👌 Improve test handling
  Makefile
  docs/release_notes/0.0.63.md
  pkg/cfn/runner_integration_test.go
  pkg/config/testing.go
  pkg/helm/helm_test.go
  pkg/kube/manifests/echoserver/echoserver_test.go
  pkg/kube/manifests/externaldns/externaldns_test.go
  pkg/kube/manifests/externalsecret/externalsecret_test.go
Labels: enhancement

#568 KM286 🐛 Fix -c only working when CWD is repo root
  docs/release_notes/0.0.63.md
  pkg/config/config.go
Labels: bug
